#!/bin/bash

logFile=$LAB_1234_LOG_FILE

createLogFile () {

	todayEpoch=$(date +%s)

	dateToday=$(date -d @$todayEpoch +'%Y%m%d')

	#echo $dateToday
	
	if [ ! -f "$logFile" ]; then
		touch $logFile
		echo "file created on : $dateToday" > $logFile
		return 0;
	fi

	epoch=$(stat -c "%Y" $logFile)
	
	dateModified=$(date -d @$epoch +'%Y%m%d')

	#echo $dateModified

	if [ $dateModified -lt $dateToday ]; then
		touch $logFile
		echo "file created on : $dateToday" > $logFile
	fi
}

startContainer () {
	
	# $1=conatiner_name   $2=COMPOSE_FILE
	#echo "$1"  "$2"
	docker-compose --file "$2" up -d "$1" 2>> $logFile
}


createLogFile

