version: "3"

services:
  apache:
    image: php:7.2-apache
    container_name: server
    restart: 'always'
    ports:
      - '9000:80'
    volumes:
      - $HOME/cse/code/apache/php/p1:/var/www/html
      - $HOME/cse/code/apache/logs:/var/log/apache2 
      #- $HOME/cse/code/apache/php/php.ini:/usr/local/etc/php/php.ini'
    #depends_on:
      #- mariadb
  
  mariadb:
    image: mariadb:10.7.3-focal
    container_name: mdb
    entrypoint: custom-docker-entrypoint.sh
    command: ["mariadbd", "--user=root"]
    #user: root
    networks:
      default:
        aliases:
          - db
    restart: 'always'
    volumes: 
      - .$HOME/cse/code/mariadb/db_dir:/var/lib/mysql 
      - ./config_files/mariadb/custom-docker-entrypoint.sh:/usr/local/bin/custom-docker-entrypoint.sh
    environment:
      TZ: "Asia/Kolkata"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cse_db"
      MYSQL_USER: "cse"
      MYSQL_PASSWORD: "password"

  adminer:
    image: adminer
    container_name: adminer
    restart: 'always'
    ports:
      - '9001:8080'
    #depends_on:
      #- mariadb

  python10:
    image: python:3.10.4-bullseye
    command: ["tail", "-F", "anything"]
    container_name: python10
    init: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $HOME/.Xauthority:$HOME/.Xauthority:ro
      - $HOME:/home/newuser

# docker-compose exec -w %d gcc11 gcc -g %f -w -o ./zz.out
# docker-compose exec -w "%d" gcc11 ./zz.out

  gcc11:
    image: gcc:11.2-bullseye
    command: ["tail", "-F", "anything"]
    container_name: gcc11
    init: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $HOME/.Xauthority:$HOME/.Xauthority:ro
      - $HOME:/home/newuser
    #network_mode: host
    #user: root

# docker-compose exec -w %d java17 javac %f
# docker-compose exec -w %d java17 java %e

  java17:
    image: openjdk:jdk
    command: ["tail", "-F", "anything"]
    container_name: java17
    init: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $HOME/.Xauthority:$HOME/.Xauthority:ro
      - $HOME:/home/newuser
    #network_mode: host
    #user:root

#xhost +
#docker run --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix 

# Libre Office AppImage: https://www.libreoffice.org/download/appimage/

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: 'always'
    volumes: 
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - $HOME/cse/code/portainer/data:/data
    ports:
      - '9002:8000'
      - '9003:9000'  #http://localhost:9003'

  vscodeserver:
    image: codercom/code-server:latest   #gitpod/openvscode-server
    container_name: vscodeserversh
    #user: "$(id -u):$(id -g)"
    restart: 'always'
    init: true
    volumes:
      - $HOME/cse/code/vscodeserver/project:/home/coder/project
      - $HOME/cse/code/vscodeserver/.config:/home/coder/.config
    environment:
      DOCKER_USER: $USER
    ports:
      - '9004:8000'

#--cap-add SYS_ADMIN --cap-add MKNOD --device /dev/fuse:mrw

